### ISSUE TITLE
Proposal: Shared Plugin Development Repository

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [stimulu/kicad-round-tracks#2]
Hello! 
This is a request for a YES/NO vote for the following proposal:
**Shared development of tools, scripts, plugins for KiCad EDA**
https://github.com/kicad-extra/arkon/issues/1
Thank you, and apologies if you already responded or otherwise not interested.

**Comment by autoiue** [comment]
Hi,

I'm willing to register and/or use plugins from a global repository (à la https://packagecontrol.io/ like for Sublime text), but I don't see a need for a global Development repo. If I do not maintain the work I choose to publish on GitHub, people are free to fork the repo and add their own modifications.

Best regards, 
Antoine

**Comment by Andrei-Pozolotin** [comment]
thank you
