### ISSUE TITLE
request for single track round option

### ISSUE THREAD

**Issue by easyw** [stimulu/kicad-round-tracks#3]
Hi, 
it would be nice to have the option to select a track and just round it.
Even better if it would be possible to click on a corner and then on a point of the same track, to choose the rounding radius.
That would be great to create round tracks only where needed and with the desired radius (i.e. for RF boards).

![](https://kicad-info.s3-us-west-2.amazonaws.com/original/2X/a/add03be79b08e4c17b32cb40b31740f7a185ea55.gif)

**Comment by autoiue** [comment]
Hi,
Thanks for the interest. This plugin is kind of a hack, I hope the KiCad team add support for arcs on copper layers. But for now we are stuck with approximating arcs with many small segments, making PcbNew laggy and track modifications extremely difficult. I hope this plugin become eventually obsolete with the futurs enhancements of KiCad.   
What could be done in the short term with the plugin is to select which nets to round and with which parameters for each net. I'll see what I can do in the coming weeks.

**Comment by easyw** [comment]
Hi @procsynth 
thanks for going into it...

> This plugin is kind of a hack, 

But a hack is better then not having a way to achieve it.

> I hope the KiCad team add support for arcs on copper layers.


I know, I'm waiting for arc support since kicad 4 :wink:
https://forum.kicad.info/t/microwave-toolbar-shape-description-file-experiences-or-documentation/2936/6
https://forum.kicad.info/t/status-on-curved-smooth-corners-in-traces/12287/18

**Comment by autoiue** [comment]
Ok this is done !

fcd4ba2dfc541b258d026bf8de322fc1c0f02bb3 implements per Net Class settings:

![Screenshot from 2019-05-14 13-08-01](https://user-images.githubusercontent.com/22014799/57694107-2cef0f00-764b-11e9-9bee-effcec4e3e5a.png)

You may want to play around `Scaling %` and `Length %` settings, `Passes` is the number of approximations to make. Defaults should be good.

Be sure that your high frequency Net is in its own Net Class.

**Comment by easyw** [comment]
Hi @procsynth , 
thanks for your prompt reply.
Would it possible to make the selection based on Net Name instead (or as an other option) to Net Class?
That would be much handier.

**Comment by autoiue** [comment]
Hi,
I think it isn't a good idea to select the settings based on the net name. Net Classes are a set of rules that apply to one or more net. It seems logical to have a Net Class dedicated to high frequency rules.
I see "roundness" has another rule. You may have multiple high frequency Nets that obey to same set of rules. I take high frequency as an example but this could be applied to other applications. 

Is there a particular reason you can't create a Net Class just for high frequency ?

**Comment by easyw** [comment]
You may need to have a single track with a defined radius on the board and an other within a different one, but they can be both on the same net class. It is more related to signal name than class in this case.
